# Site wide configuration

title: atframework
description: "Cloud server solution for game developer based atframework."
logo: logo-m.png # 120x120 px default image used for Twitter summary card
teaser: default-teaser.png # 400x250 px default teaser image used in image archive grid
locale: en
url: # "atframe.work"
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:year-:month-:day/:title.html

kramdown:
  input: GFM
  auto_ids:      true
  extensions:
    - autolink
    - footnotes
    - smart
  toc_levels: 1..3
  hard_wrap: true
  html_to_native: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    linenos: true

highlighter: rouge
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-paginate

paginate: 20

# Site owner
owner:
  name: "owent"
  email: "admin@owent.net"
  twitter: 
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: owner-logo.jpg # 160x160 px image for author byline
  disqus-shortname:


include:
  - .htaccess

exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp

include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      author_profile: true